### ISSUE TITLE
Build CI on macos-latest

### ISSUE THREAD

**Issue by Coloquinte** [rust-or/highs#11]
Highs doesn't build using Github CI on macos-latest (see [complete log](https://github.com/Coloquinte/highs/actions/runs/7370745086/job/20057558054)).

The error is `ld: library not found for -lomp`, which seems related to [this stackoverflow thread](https://stackoverflow.com/questions/44579856/ld-library-not-found-for-lomp), where the proposed solution is to provide the full path for `libomp.dynlib`.

I have no idea how to make this work transparently when installing the crate, but it would be nice to have.

**Comment by lovasoa** [comment]
Yes, that would be nice to have indeed! Can you make a pull request?

**Comment by jajhall** [comment]
HiGHS doesn't need OpenMP - and hasn't for 2-3 years

**Comment by lovasoa** [comment]
Wow, then we should probably update https://github.com/rust-or/highs-sys/blob/master/build.rs

@jajhall , could you have a look and check whether there are other things we should update there ?

**Comment by Coloquinte** [comment]
So if we don't need to build with OpenMP at all maybe we can just remove the `cargo:rustc-link-lib=dylib=omp` option from the `highs-sys` crate.

At the moment my workaround to build is the same as for `highs-sys`, using `brew link --force libomp`

**Comment by jajhall** [comment]
> Wow, then we should probably update https://github.com/rust-or/highs-sys/blob/master/build.rs
> 
> @jajhall , could you have a look and check whether there are other things we should update there ?

Could you have a look at this @galabovaa

**Comment by Coloquinte** [comment]
Trying this right now

**Comment by Coloquinte** [comment]
Great, thanks!
