### ISSUE TITLE
model.set_option does not work for I/O options

### ISSUE THREAD

**Issue by alaasfarhat** [rust-or/highs#13]
Hello, 

while using the crate, we can send options to the solver via model.set_options('option_string',value), we can control some of the options from here however when we need to write the solution file and/or the model file, nothing happens.

Other than that we do think that the crate is very easy to use, and appreciate all the work that has been put into it :).

Best regards

Alaa

**Comment by lovasoa** [comment]
Those options do not concern highs when used as a library.
If you have a model file and want the solution written to a solution file, then you don't need a library and can use the highs binary directly.

**Comment by alaasfarhat** [comment]
hi,

thanks for your answer, maybe I did not explain the issue correctly,  
 
We do not have a model file we are creating the problem and solving the model using the highs library, and we do collect the results in the code, however sometimes for comparison purposes  the model file in .lp format is helpful due to its portability to test on other machines/solvers.

For the solution file, we do not need it per se, but when i was trying to pass the option, it did not work.   

Best

Alaa
