### ISSUE TITLE
Unfeasilble with highs, solved with lpsolve

### ISSUE THREAD

**Issue by nunzioono** [rust-or/highs#16]
Hi, i've been writing for some time a program using good lp, i've a model with 2k rows of constraints and while i've implemented it in good lp using the highs solver specified in the features it gets detected as unfeasible. On the other hand if i debug the same model printing it as an lp file and pass it within lpsolve ide it gets solved specifying that some of the constraints are redundant. I wonder if this can be a feature to be added or should be classified as a presolve bug in the highs crate/module since, as me, i believe many models can be represented using "implicitely" redundant constraints. As implicit i mean bounds that in some solution result as redundant and changing a parameter in the problem (another bound), are no more redundant.

**Comment by jajhall** [comment]
Let's discuss this on https://github.com/ERGO-Code/HiGHS/issues/1756

**Comment by jajhall** [comment]
This was not a bug in HiGHS, but the result of confusing lpsolve behaviour
